### ISSUE TITLE
Creating Circuit for buttons

### ISSUE THREAD

**Issue by RubenBelligh** [vives-project-xp/HandheldRetropie#16]

**Comment by RubenBelligh** [comment]
Find out how to connect the buttons to the PI.

**Comment by RubenBelligh** [comment]
Find out how to connect the buttons to the PI.

**Comment by RubenBelligh** [comment]
Draw a circuit for the buttons.

**Comment by RubenBelligh** [comment]
Searching for a solution to too few pins on the Raspberry pi. (solution I/O expander).

**Comment by RubenBelligh** [comment]
I made a circuit for the buttons with an I/O expander because there weren't enough pins. Now there is only 1 problem to get to the 3V3 pin, the display is already connected there.

**Comment by BanaantjeJowie** [comment]
solution found for too few pins and buttons work on breadboard
