### ISSUE TITLE
Making a working product

### ISSUE THREAD

**Issue by RubenBelligh** [vives-project-xp/HandheldRetropie#18]

**Comment by RubenBelligh** [comment]
Afwrijven van het 3D design zodat het niet meer zo ruw aanvoelt.

**Comment by RubenBelligh** [comment]
Bovenkant aan elkaar geplakt

**Comment by RubenBelligh** [comment]
Moertjes geplakt aan de controller en dan de verschillende onderdelen bevestigd.

**Comment by Tbo-s** [comment]
Solderen van de knoppen, weerstanden en draden op de PCB.

**Comment by Tbo-s** [comment]
PCB in de controller plaatsen.

**Comment by Tbo-s** [comment]
Batterijhouders in de controller plaatsen en deze solderen op de pcb.

**Comment by RubenBelligh** [comment]
Batterijen plaatsen en alles een plaats geven in de controller.
