### ISSUE TITLE
Instructions fusion 360

### ISSUE THREAD

**Issue by Tbo-s** [vives-project-xp/HandheldRetropie#5]
Making instructions of how to make and start with a Fusion 360 project. This is being done in word.

**Comment by RubenBelligh** [comment]
Het eerste hoofdstuk geschreven hoe je de studenten licensie kan verkrijgen en hoe je autodesk fusion moet downloaden.

**Comment by RubenBelligh** [comment]
Beschrijven welke functies ik gebruikt heb in fusion 360 om mijn controller te maken.
