### ISSUE TITLE
Documentation Test components

### ISSUE THREAD

**Issue by RubenBelligh** [vives-project-xp/HandheldRetropie#50]
Bevindingen van de testen documenteren

**Comment by BanaantjeJowie** [comment]
pwm fans werken zoals het hoort

**Comment by BanaantjeJowie** [comment]
spanningsregelaar is getest en we zijn tot de conclusie gekomen dat we de verkeerde hebben besteld

**Comment by BanaantjeJowie** [comment]
drukknoppen werken zoals het hoort met de raspberry pi

**Comment by BanaantjeJowie** [comment]
nieuwe spanningsregelaar is getest en werkt volgens verwachtingen

**Comment by BanaantjeJowie** [comment]
pwm signaal (uit de raspberry pi) om de fans aan te sturen uitgemeten en werken volgens verwachtingen. Eventuele aanpassingen aan parameters kunnen gemaakt worden met ssh verbinding met de rpi

**Comment by BanaantjeJowie** [comment]
batterijenpacks zijn getest met 18650 batterijen met een spanning van 4V per batterij, 8V per 2.
ook zij deze getest met de spanningsregelaar en deze werkt volgens verwachtingen
