### ISSUE TITLE
Documentation of Pins Used

### ISSUE THREAD

**Issue by Tbo-s** [vives-project-xp/HandheldRetropie#61]

**Comment by BanaantjeJowie** [comment]
Button pins can be accessed using this line in console : `sudo nano /boot/retrogame.cfg`
The rest of the pins are found in `script.py`
**PINS USED:**
`
LEFT       4  # _Joypad left_
RIGHT     19  # _Joypad right_
UP        16  # _Joypad up_
DOWN      26  # _Joypad down_
LEFTCTRL  14  # _'A' button_
LEFTALT   15  # _'B' button_
Z         20  # _'X' button_
X         18  # _'Y' button_
SPACE      5  # _'Select' button_
ENTER      6  # _'Start' button_
A         24  # _Left shoulder button_
S         13  # _Right shoulder button_
ESC       17  # _Exit ROM; PiTFT Button 1_


PWM      12 # PWM signal for fans


`
**will be edited**
